[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = "0.7.5"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
opt-level = "s"